[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["bench", "fuzz"]

[workspace.dependencies]
five8.path = "crates/five8"
five8_const.path = "crates/five8_const"
five8_core.path = "crates/five8_core"
