[package]
name = "five8"
version = "0.1.0"
edition = "2021"
resolver = "2"

[features]
dev-utils = []
std = []

[dependencies]
five8_core.workspace = true

[dev-dependencies]
bs58 = "0.5.1"
five8 = { path = ".", features = ["std"] }
five8_const = { workspace = true }
proptest = "1.5.0"
